### ISSUE TITLE
Update cap_reference.pdf to newest version

### ISSUE THREAD

**Issue by yutotakano** [compsoc-edinburgh/betterinformatics#114]
The Year 1 cap_reference.pdf file hasn't been updated since 4 years ago, however the upstream repo on compsoc-edinburgh/bi-cap has been updated by joe and qaisjp about a year and a half ago. That needs to be reflected.

**Comment by qaisjp** [comment]
Probably worth just getting rid of the notes altogether.

**Comment by qaisjp** [comment]
Probably worth just getting rid of the notes altogether, 4 years old notes feels a little bit past the expiry date to me. Or are you finding it useful?

**Comment by qaisjp** [comment]
Alright [according to Discord](https://discord.com/channels/315277951597936640/315278744572919809/805611395831300097), people are finding it useful.

I think we should just upload the PDF to GitHub releases on the bi-cap repo instead of inside this git repo, though.

(We should try to avoid storing PDFs directly inside the repo as binary files can make the repo size huge over time.)

**Comment by yutotakano** [comment]
> Or are you finding it useful? 

It's definitely a great way to quickly review in an entertaining way. Since the textbook has been the same (Stewart, 2013) all these years, I think the notes are still very much applicable. Even the exercise numbers listed match the ones given by our course organisers.

I agree that avoiding big binaries in the repository is a good idea. My thought is that regardless of where the binary itself is, we should update betterinformatics to point to the new location, for it helps when quickly referring to it or sharing with a friend. Saying "it's on the betterinformatics website" is easier than having to tell them to navigate through an obscure github repository. Perhaps we could make the link on the Year 1 page point to the direct download from Releases? i.e. https://github.com/compsoc-edinburgh/bi-cap/releases/latest/download/reference.pdf

**Comment by qaisjp** [comment]
Good idea! I've invited you to the org (the invite might show up [here](https://github.com/compsoc-edinburgh), otherwise check your emails), so you can just go ahead and do that :)

I think there's a link in the `bi-cap` document itself that needs updating. Lovely circular references.
