### ISSUE TITLE
Can you add me as contributor 🥺 👉 👈 

### ISSUE THREAD

**Issue by benedictusalvian** [compsoc-edinburgh/betterinformatics#122]
Thank you so much <3

**Comment by penalosa** [comment]
@ChefYeum why have you marked this `invalid` and `wontfix`? This is the right way to request permissions (see the README)

**Comment by penalosa** [comment]
@benedictusalvian I’ve added you now 🙂

**Comment by ChefYeum** [comment]
@penalosa for a laugh

**Comment by penalosa** [comment]
Do you know each other outside of this issue? Because unless you're both in on the joke, it's probably best to try to refrain from having a laugh at the expense of new contributors, if possible.

**Comment by ChefYeum** [comment]
@benedictusalvian Sorry for any offence caused. On a serious note, please continue to contribute to the docs.
