### ISSUE TITLE
betterinformatics.com down?

### ISSUE THREAD

**Issue by v-raja** [compsoc-edinburgh/betterinformatics#127]
Any idea why the site could be down? (Or is it just me?)

**Comment by kshxtij** [comment]
Works for me

**Comment by v-raja** [comment]
Weird, wonder if it has something to do with the fact that I'm trying to access it from AT.

**Comment by mayacopeland** [comment]
If memory serves me right betterinformatics doesn't play nicely with eduroam

**Comment by oxrush** [comment]
BI is still on Tardis I believe, and I don't think the issue of web traffic between eduroam and Tardis being blocked was ever resolved.

**Comment by carlinmack** [comment]
I thoght I head that tardis is being EOL'd?

**Comment by oxrush** [comment]
We have to have Tardis as it exists now shut down by February 25th 2022. We're looking to replace it going forwards but BI might be migrated off Tardis before then.

**Comment by qaisjp** [comment]
Vivek, what DNS do you use? Better Informatics is not down right now.
