### ISSUE TITLE
Suggest a resource for experimenting with regular expressions /_sections/inf1/inf1-cl.md

### ISSUE THREAD

**Issue by cyrilbois** [compsoc-edinburgh/betterinformatics#135]
Hello,

I would like to suggest a resource for learning and experimenting with regular expressions:
https://extendsclass.com/regex-tester.html  (Regex tester and visualizer)

This is to add to section "Regular Expressions" of page /_sections/inf1/inf1-cl.md.

**Comment by qaisjp** [comment]
my favourite resources here are:

https://regexr.com/
https://regex101.com/
