### ISSUE TITLE
Could I please be added as a contributor?

### ISSUE THREAD

**Issue by cem-yilmaz** [compsoc-edinburgh/betterinformatics#136]
I'd love to add my revision notes as a link to OS (and FNLP, when I get around to it after the exam).

Thanks

**Comment by yutotakano** [comment]
Done! Just an FYI that you can also just upload your notes to [files.betterinformatics.com](https://files.betterinformatics.com) without any special permissions as long as you are a student, that's the recommended way to share non-link resources!

**Comment by cem-yilmaz** [comment]
Thanks :)

I was trying to link to the repository of my notes in the Communuity Knowledgebase section, which after some searching, I unfortunately cannot find any other means of uploading without editing the document on GitHub. Hope this is ok, Am I mistaken here?

**Comment by yutotakano** [comment]
Ah in that case it's the correct approach! We'd love to make this repo publicly writable for everyone but because of risk of spam we had to set a whitelist requirement. In the future there might be some integration with File Collection so you can edit in-page without a GH account, but who knows!
