### ISSUE TITLE
Short guide for new infers. 

### ISSUE THREAD

**Issue by Visgean** [compsoc-edinburgh/betterinformatics#20]
I would have find it useful to have a short guide describing what we are going to study. 

- List of Calculus and Linear algebra chapters that are covered in first year
- Links to Khan academy
- Links to CompSoc 

We should do this after exams.

**Comment by pecoraa** [comment]
@Visgean Chapters covered are different each year, Khan academy is kind of easily found through first google links. CompSoc what?
I agree we can write a guide, but perhaps different topics?

**Comment by qaisjp** [comment]
We can add the stuff @Visgean mentioned to the respective sections. For an actual guide we can [make use of this](toaster.cc/inf4-hci-2/). The owner says that we can use it. They'll soon be adding a license.

**Comment by Visgean** [comment]
Yeah, I mean it would be good to set it up on some new domain and add some other content.

**Comment by qaisjp** [comment]
We're moving to betterinformatics over the next few weeks!

**Comment by qaisjp** [comment]
welcome.betterinformatics.com is something
