### ISSUE TITLE
potential expansion for maps

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/betterinformatics#26]
http://www.ed.ac.uk/maps/maps is pretty nifty

- ["api"](http://webproxy.is.ed.ac.uk/web-proxy/maps_edweb/data.php)
- [script for reference](http://webproxy.is.ed.ac.uk/web-proxy/maps_edweb/js/map-ajax.js)

**Comment by aptgetmoo** [comment]
I'm not sure it'd be totally worth putting *all* the buildings on the map -- but maybe the key (Informatics) ones like AT (already there), 50 GS (because lectures), the old medical school, and so on.

**Comment by Visgean** [comment]
Yeah, i agree, we can also link for the full map. But we should keep it relevant.

**Comment by aptgetmoo** [comment]
@Visgean do you think it's worth trying to implement their system or just add the relevant places via the .geojson file?

**Comment by Visgean** [comment]
I think we should just add some of their places to the geojson. We can use some icons and colors but I dont think we should add too many buildings.

**Comment by aptgetmoo** [comment]
I agree!

**Comment by aptgetmoo** [comment]
If we end up doing this, it's worth mentioning this is changing maps from *study spaces*, to a general map.
