### ISSUE TITLE
RFC: a page for DICE notes

### ISSUE THREAD

**Issue by aptgetmoo** [compsoc-edinburgh/betterinformatics#27]
There are a few things that are almost FAQ's with fixing dice (like not being able to log in).
If such a repository of issues exists, should BI link to it?
If not, should BI provide some common problems?

Stuff that I would put in there:

* Black screen on login / WM crashing on login
* Getting audio to work

**Comment by qaisjp** [comment]
sounds like something for the start page, or the page could atleast be linked on the start page 

/assign @aptgetmoo

**Comment by aptgetmoo** [comment]
think a new page within BI or something hosted elsewhere?

**Comment by qaisjp** [comment]
perhaps something like this? https://github.com/compsoc-edinburgh/betterinformatics/blob/master/resources/inf1-fp/install.md but not in the inf1-fp folder?

**Comment by qaisjp** [comment]
done https://github.com/compsoc-edinburgh/betterinformatics/blob/master/resources/dice.md
