### ISSUE TITLE
Archive old courses

### ISSUE THREAD

**Issue by mehii** [compsoc-edinburgh/betterinformatics#28]
Cleaning up some basic stuff in 3rd year I've found quite a few courses are either not available from 2015-2016 or are completely missing from the DRPS. I'm guessing this applies mostly to year 3+ when all the selective courses start.

**Suggestion:**
Get them all in one folder and keep for future uses (if ever). Feels a bit of a shame to just chuck all the resources (links, docs etc. ) away. 

Anything else that could be archived or cleaned up from the website? Mostly to make it less cluttered.

**Comment by qaisjp** [comment]
use `archived: true` :) 

it should then disappear :sparkles:

**Comment by mehii** [comment]
I would give you all the stars of the night if I could
