### ISSUE TITLE
Add course acronyms to Inf4 courses

### ISSUE THREAD

**Issue by neanias** [compsoc-edinburgh/betterinformatics#31]
Also add `semester`s and `archived` bools

**Comment by mehii** [comment]
Would also be curious to hear ideas how to direct people to Year 3 courses they can still take in 4th year.

**Comment by neanias** [comment]
Maybe add a 'UG3/4' marker at the top and highlight it? A sort of yellow button thingy?


On 29 Sep, 2017, at 01:06 PM, Vik <notifications@github.com> wrote:



Would also be curious to hear ideas how to direct people to Year 3 courses they can still take in 4th year.

**Comment by qaisjp** [comment]
this is how we handle those situations right now: https://betterinformatics.com/inf4#abs

https://raw.githubusercontent.com/compsoc-edinburgh/betterinformatics/b92062c3697dc8dd13af1e29d4790a5c549e29d2/_sections/inf4/abs.md

it's not too pretty as you have to manually create redirections. this way it shows up in the listing with a link to the actual content.

**Comment by qaisjp** [comment]
Just gave the link a test and as you can abs has been archived, the counterpart version on inf4 still lives on even though it doesn't exist on inf3.

A working version is actually here: https://betterinformatics.com/masters#ar

Might be good to have something like

```
# this would be in inf3/abs.md
include:
    - inf4 # this would make it so that the inf3 course also appears on inf4
```

**Comment by neanias** [comment]
God above, that page is huge. I think we need a bit of a redesign or some sort of TOC/sidebar

**Comment by qaisjp** [comment]
@neanias indeed. i'm hoping we can rewrite the website in bootstrap whilst maintaining the whole look and feel. that way we can leverage bootstrap's tabbing feature (and other useful utilities..) to separate the courses by semester

**Comment by neanias** [comment]
I think the collapsible sections is also a good idea, then at least someone can see several courses at once, rather than the tabbing

**Comment by mehii** [comment]
Basically a lot of improving of everything. YAY

**Comment by neanias** [comment]
Anyone game to wait until October? T-shirts! T-shirts for everyone!

**Comment by qaisjp** [comment]
it's october.

**Comment by neanias** [comment]
Duly noted

**Comment by qaisjp** [comment]
any updates?

**Comment by neanias** [comment]
Getting cracking now

**Comment by neanias** [comment]
Is there any sort of flag for courses that are not currently running?

**Comment by qaisjp** [comment]
"archived"
