### ISSUE TITLE
Add information on remote access to DICE

### ISSUE THREAD

**Issue by vaidap** [compsoc-edinburgh/betterinformatics#45]
Students are never taught how to SSH & this ends up impacting coursework (students believe they have to be at AT to work on DICE-specific coursework), as well as not using `student.compute` like they should. I think it would be great to have a guide to SSH-ing and other options for remote access on the site.

I've started on a small guide over here: 
https://gist.github.com/vaidap/41ff0abaa8ab35c771568dd129114f3a
(I am by no means an expert, learnt how to `sshfs` a few weeks ago and it blew my mind & I now need to share it with the world)

Let me know if this is something that would be good to have/add to the site. Feedback on what to cover/which commands to use/commands for alternative OSes greatly appreciated. :)

**Comment by neanias** [comment]
I’d say this is a good idea. Couple of quick notes on the Gist:

* `less` just previews the file rather than allowing editing
* A cheat sheet or quick guide might be useful for people to quickly pick up and play
* I think it would be good to heavily signpost `sshfs` as advanced usage

**Comment by vaidap** [comment]
thanks for the feedback, I added notes on the gist to reflect them.
quick question, why would `sshfs` be advanced-- are there big mistakes/issues beginners might have?

**Comment by neanias** [comment]
I think it's better to highlight basic usage first, then add new things once the users feel comfortable (such as `sshfs` and X11 forwarding). My suggestion would be to have 'SSH' as the heading as you have, then a sub-heading of 'basic usage', then another sub-heading of 'more advanced usage' or something to that effect. I'd definitely say to add this though! Get a pull request open so we can add it.

**Comment by neanias** [comment]
Oh, also, when they're SSH-ed in, they can just run `ssh student.compute` to reach the Compute server, no need for the `inf.ed.ac.uk`.
