### ISSUE TITLE
Google drive link not working - 502 error

### ISSUE THREAD

**Issue by BenBanerjeeRichards** [compsoc-edinburgh/betterinformatics#56]
To reproduce:

1. Go to [https://betterinformatics.com/](https://betterinformatics.com/)
2. Press "Team drive" button at top of page
3. (if not logged in to cosign yet) Login using dice credentials

After logging in you are redirected to cloudflare error page:

![image](https://user-images.githubusercontent.com/5972559/40886389-ed1a7986-672e-11e8-8657-c3d3540f26a1.png)

Tested in Google chrome and Microsoft edge, both windows 10

**Comment by qaisjp** [comment]
Hey, thanks for the report.

Unfortunately we have some issues with cosign authentication at the moment
so we'll just have to wait until our firewall issues are sorted out.

Sorry!

**Comment by qaisjp** [comment]
FYI if you want me to add your account to the drive, just gimme your Google
account email address and I can add it from my side.

(Then it will just show up on Google Drive for you)

**Comment by BenBanerjeeRichards** [comment]
I don't need anything from the drive, just something I noticed when poking around

thanks!

**Comment by qaisjp** [comment]
this has since been solved.

the problem turned out to be an update on Informatics' side which we hadn't gotten wind of. a certificate update for our cosign filter fixed this.

thanks again for your report!
