### ISSUE TITLE
Past Paper Index

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/betterinformatics#82]
Provide an index of past papers and their (attempted) solutions for every course.

- Should be a dropdownsearch to select/find the course you want.
- Should contain links to exampapers.ed.ac.uk and the corresponding solutions in Google Drive
- Should _probably_ support tracking of older versions of courses.
    - Why: DRPS codes changed when course levels were changed from `10` to `20` in 2016.
    - Side effect: Because of the reduction in Drive exploration, users will not notice the "old" solutions.
    - Implementation: simply create a `course_history.yml` file and map "current codes" to an array of "old codes"

Reasons for:

- Nicer to have links to questions and answers on one page
- For a number of courses we store copies of question papers on our drive. I want to get rid of this needless mirroring of PDF files.
    - IMO it's wasteful (of an infinite resource) and requires maintenance (because they exist).
    - **Needs discussion: please tell me whether you find the _question paper_ folders useful, and explain why.**

Reasons against:

- Introduction of this feature will result in less exploration of the Drive, which is bad! Maybe we want to change this into a "Drive Index"?
- Some people may find PDF paper access via Google Drive easier
    - Personally, I actually find exampapers.ed.ac.uk better because the PDF is opened directly in my browser, instead of embedded within a Google Drive page

**Comment by AlexPietz** [comment]
Different people have different ways of dealing with papers & attempted solutions. For example, some people (me included) like taking partial screenshots from the original PDF and discussing the solution underneath; all in a drive document. Others may prefer commenting on the original PDF. The drive can also be nice if you want to print out all/multiple previous papers from the same course. 

The question is what the point of the index is? Simply to generate a searchable question bank?

**Comment by AlexPietz** [comment]
> IMO it's wasteful (of an infinite resource)
Yes, I agree. Is the university obliged / do they guarantee hosting in the future?
> and requires maintenance (because they exist).
The proposed solution would arguably require more maintenance. Is there one person that is supposed to maintain the whole list or do you leave it up to whoever people are in a particular course? Some courses may be neglected (some already are).

**Comment by qaisjp** [comment]
> Different people have different ways of dealing with papers & attempted solutions.

I guess eventually what would be nice would be some kind of standardisation.


> For example, some people (me included) like taking partial screenshots from the original PDF and discussing the solution underneath; all in a drive document.

I like this approach! For OS, the questions were just copied out into the Doc in bold and reformatted to be a little cleaner. Some figures were screenshotted and pasted in.

> Others may prefer commenting on the original PDF.

I've never seen this! Do you have an example?



> Yes, I agree. Is the university obliged / do they guarantee hosting in the future?

Good question. We should find out.

Computer Security goes back to May 2002 on the Drive. On exampapers, it goes back to May 2005.

I would excuse the fact that exampapers is missing May 2002 and May 2003 (which we have on Drive), since those are actually "Computer Science Four: Computer Security", which is a complete different generation of courses.

Oddly enough, May 2004 (on Drive), titled "Computer Security" is missing on exampapers. But that paper also says its for 4th years and MSc students. So I guess that's the year between making Computer Security available to 3rd years, and the year they had Computer Science 1A/1B/2A/2B etc.

(This could all be verified by a nice visit to DRPS, but I am a little lazy right now.)

I do not want us to delete papers that are unavailable on exampapers, for sure.

IMO there's _little_ point in studying from papers that go THAT far back -- but then again, when I was at school, I did maths past papers that released in my birth year... and it was still mostly relevant. So they should still be kept around for the students that want those papers.


> The question is what the point of the index is? Simply to generate a searchable question bank?

Not a searchable question bank (although that is not a bad idea...), but just a table like this for each course:

```
Key:
- `gold`: complete and answers verified to be correct
- `silver`: complete but contains mistakes
- `bronze`: incomplete

Course: INFR10yada Computer Security

Exam         | Questions | Solutions | Status
-------------|-----------|----------
August 2018  | questions | solutions | gold
May 2018     | questions | solutions | bronze
August 2017  | questions | solutions | silver
May 2017     | questions | solutions | gold
August 2016  | questions | solutions | gold
May 2016     | questions | solutions | gold

- `questions` above is a link to exampapers.ed.ac.uk
- `solutions` above is a link to the Google Doc, which also contains the questions copied over
```

e.g. Operating Systems has some good "gold" solutions, but Software Testing has many "silver" solutions.

This would achieve a few things:
- both questions and solutions can be accessed from one page (instead of two folders, like many subjects currently have)
- ratings on how question papers are
- some guidance/tips can be put on this page for how to write solutions effectively

> The proposed solution would arguably require more maintenance. Is there one person that is supposed to maintain the whole list or do you leave it up to whoever people are in a particular course? Some courses may be neglected (some already are).

Actually, yeah, you are right. The idea is that it is left up to whoever is on the particular course (with some initial work done by me and hopefully others to bring it up to date).

I think the biggest the barrier is getting people to edit the page. People find it easier to upload to the Drive than to edit Better Informatics.

If we enforced a directory structure, we could maybe automate the solutions list (requiring just the "Status" and "Questions" fields to be provided)?

> The drive can also be nice if you want to print out all/multiple previous papers from the same course.

Because all _direct_ links are in the same place, this actually becomes easier. Ctrl+Click on all the question papers you want, and they all open in a new background tab. You can't Ctrl+Click on Google Drive. 

What we would lose out on, however, is the ability to select multiple files and have Google Drive generate a zip file with those question papers.

**Comment by AlexPietz** [comment]
>I guess eventually what would be nice would be some kind of standardisation.

Agreed. There should be some centralised CONTRIBUTING instructions.

> Some figures were screenshotted and pasted in. 

This makes a lot of sense for figures, graphs, code listings, etc. as they don't always convert nicely.

>>Others may prefer commenting on the original PDF.
>
>I've never seen this! Do you have an example?

The example I was thinking of was outside of BI, it was a multiple choice exam and the annotations were to signify which answer was (thought to be) 

> IMO there's little point in studying from papers that go THAT far back

Agreed. There may still be some value to archiving the papers.

*Re Index:*
> both questions and solutions can be accessed from one page (instead of two folders, like many subjects currently have)

Got it and agree.

> ratings on how question papers are

Might be hard to enforce specific ratings as they may be subjective (especially for courses where there usually isn't ONE correct answer, e.g. Usec). Might be possible to replace / add some sort of metric to this that signifies the maturity of the solutions. E.g. paper from 4 years ago for popular course will have more mature solutions (more peer reviews) than a paper of the same age for some obscure course not many people take.

> some guidance/tips can be put on this page for how to write solutions effectively

Agreed.
A searchable question bank would be cool but might be too much work for the utility it would provide.

> automate the solutions list 

Would be cool to pull new papers from exampapers.ed.ac.uk though this is gated behind cosign and some in-scope courses may not follow the clear INFR12345 coding.

**Comment by qaisjp** [comment]
> The example I was thinking of was outside of BI, it was a multiple choice exam and the annotations were to signify which answer was (thought to be)

Yeah, this seems like a pretty smart solution. I suppose in this case the solutions linked would just be annotated/commented question papers.



> Might be hard to enforce specific ratings as they may be subjective (especially for courses where there usually isn't ONE correct answer, e.g. Usec). Might be possible to replace / add some sort of metric to this that signifies the maturity of the solutions. E.g. paper from 4 years ago for popular course will have more mature solutions (more peer reviews) than a paper of the same age for some obscure course not many people take.
> 

I think your suggestion is a better idea.

- Polished (matured solutions)
- Unreviewed (fresh :ok_hand: solutions that haven't really been "verified")
- Incomplete (
- Missing

Although generally courses like USec could choose to deviate from these guides.

> A searchable question bank would be cool but might be too much work for the utility it would provide.

This would be implementable if we replaced the entire Google Docs system of writing past paper solutions. Someone [tried that before](https://github.com/maccery/pastpapers) (graduated end of 2016/17) by converting their honours project, but it was written in PHP (ew) and hard to deploy (I tried with difficulty). Happy to look into this - we have a license for multi-user document editing - but not sure if it's worth it in terms of maintenance cost beyond our lives.

> Would be cool to pull new papers from exampapers.ed.ac.uk though this is gated behind cosign and some in-scope courses may not follow the clear INFR12345 coding.

... I'll send a ticket to the Central IS and see if there's some sort of exampapers API... and maybe see if we can get a perpetual service account. Very much doubt we would get this though, but would be great. Should probably first speak to Informatics computing support and hear their POV before going above them.

**Comment by yutotakano** [comment]
I'm revisiting this issue after my exchange to ETH Zürich where I found their website for past paper community solutions *extremely* well designed (exams.vis.ethz.ch). It's maintained by the computing society there, although there's a tighter coupling with the uni staff there than here. They have now released their whole system as GPL and I'm very much keen on trying it out for UoE Inf.

Feature set:

- Admins upload PDFs for each course, which they can cut into vertical segments (for each question) - each segment gets a comment section on the website to write solutions
- You can sort by course and year
- The comments/solutions can be upvoted if it helps you, which allows students to see how accurate an answer might be
- The comments can use LaTeX for maths
- Past paper PDFs for new courses are either directly obtained by the admins from the course organisers, or are donated by members with the consent of professors
- Admins can hide courses or PDFs at will, if they are not yet ready for public

This feels like a more friendlier solution than GDrive Discussion documents (suggested above). It could be at e.g. `exams.betterinformatics.com`.

However, its use is exclusive to past papers though, which means the other content hosted on BI Drive (tips, cheatsheets) might become less used/obvious.

Does anyone have thoughts?

**Comment by yutotakano** [comment]
Screenshots of their interface since some of it is behind a login-wall. (Speaking of which, they are able to use their uni LDAP system since it's hosted on ethz.ch -- we aren't able to do that with BetterInformatics and it doesn't look like we're going to be allowed to use EASE or DICE logins anytime soon, so we'll need another auth method if going with this)

Collapsed
![msedge_2023-08-20_12-31-16](https://github.com/compsoc-edinburgh/betterinformatics/assets/60749079/b3f0ce96-0519-4b77-9d36-66db0620effa)

Expanded
![msedge_2023-08-20_12-31-24](https://github.com/compsoc-edinburgh/betterinformatics/assets/60749079/9f6d26ec-a0d8-4ff8-9f06-a9b5f56cba1f)

**Comment by qaisjp** [comment]
looks good and sounds great!

**Comment by yutotakano** [comment]
I've written up a proposal document for migrating BI files from Google Drive to a dedicated exam collection / past paper index. The name is yet to be decided, but the plan is to do the engineering work and migration throughout early this semester, and put it through test during the autumn exam season. Could all interested parties take a look? I've linked a demo instance too.

https://docs.google.com/document/d/1GNcChsJYa-jKhWEzOWU7Ebba9K15rY0kJ_yZQi6ZxR4/edit?usp=sharing

**Comment by yutotakano** [comment]
The proposal above has now been followed through and has now been implemented and launched at https://files.betterinformatics.com. We're seeing good use this exam season with around 500 registered users. While it's an added technology burden, I'm currently securing admins for the next few academic years so hopefully it'll keep us rolling.

The source code, CI, the hosting infrastructure (Kubernetes), and database backups are  is on Tardis, with a mirror here: https://github.com/compsoc-edinburgh/edinburgh-community-solutions

<details>
<summary>Screenshots</summary>

![msedge_2024-05-05_14-01-33](https://github.com/compsoc-edinburgh/betterinformatics/assets/60749079/21ce8c09-4b2c-452f-b3be-3b8eb168906e)
![msedge_2024-05-05_13-58-26](https://github.com/compsoc-edinburgh/betterinformatics/assets/60749079/81d31f1b-4156-45a6-b91b-1d22f7bb1519)

</details>
