### ISSUE TITLE
Replace MathJax with Katex

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/betterinformatics#86]
I vaguely recall adding MathJax to some pages a few years ago, but I don't remember which.

Please can someone search & replace with https://katex.org/?

Cheers

**Comment by parna86** [comment]
https://github.com/compsoc-edinburgh/betterinformatics/blob/84799af19018615ee02a3bbc9926dd7024ede021/_layouts/default.html#L55  Found one occurrence of MathJax here - wasn't sure if the replacement to be done was just this script tag?

**Comment by qaisjp** [comment]
You can probably just remove the script tag, and if we find something trying to use it, we can fix it later
