### ISSUE TITLE
improve links for external courses

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/betterinformatics#87]
this

https://betterinformatics.com/inf2#pwa-probability-with-applications

is a pretty shitty link

**Comment by rphi** [comment]
Pretty sure this should be using the course acronym if there is one:
https://github.com/compsoc-edinburgh/betterinformatics/blob/d9b9b266c1a887ed8254e1729da6ef333635130e/_layouts/section.html#L16

**Comment by rphi** [comment]
Yup, just a front matter issue for that course, should be https://betterinformatics.com/inf2#pwa. See PR.

**Comment by qaisjp** [comment]
The issue here is that the course-acronym refers to the acronyms at https://course.inf.ed.ac.uk. 

That's exported to [/_data/courses.yaml](https://github.com/compsoc-edinburgh/betterinformatics/blob/master/_data/courses.yml) and [courses.json](https://betterinformatics.com/courses.json).

Later on we might "auto-archive" courses with acronyms that aren't in that list, since they aren't running that year, instead of manually doing `archive: true`.

PWA isn't an Inf course and so doesn't have an acronym. Same situation for Speech Processing (inf4, inf3, or inf5, not sure), Logic 1 (inf2), and I think a few others.
